create extension if not exists vector;

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  embedding vector(1536) not null
);

alter table public.documents enable row level security;

create or replace function public.match_documents(
  query_embedding vector(1536),
  match_count int default null,
  filter jsonb default '{}'::jsonb
)
returns table (
  id bigint,
  content text,
  metadata jsonb,
  similarity float
)
language sql
stable
as $$
  select
    documents.id,
    documents.content,
    documents.metadata,
    1 - (documents.embedding <=> query_embedding) as similarity
  from public.documents
  where documents.metadata @> filter
  order by documents.embedding <=> query_embedding
  limit match_count;
$$;

create index if not exists documents_embedding_idx
on public.documents
using ivfflat (embedding vector_cosine_ops)
with (lists = 100);

-- The backend uses SUPABASE_SERVICE_ROLE_KEY, so this table is not exposed to
-- the browser. Add stricter RLS policies if browser-side document access is needed.
